<!--
 *
 * Message template
 *
 * Variables available:
 * $this->date = Current date
 * $this->time = Current time
 * $this->site_name = Site name as configured in form.process.php
 * $this->site_logo = Path to site logo as configured on form.process.php
 *
 * Other variables are
 * generated by the contact
 * class based on the input IDs
 * e.g. input ID "name" would
 * generate $this->name as a variable.
 *
-->
<!doctype html>
<html>
<body style='font-family: Helvetica Neue, Arial, sans-serif; font-size: 16px; font-weight: 300; height: 100vh; margin: 0'>

<div style='background: #efefef;'>
    <div align='center' style='padding: 40px'>
        <table cellspacing='0' cellpadding='0' border='0' style='font-family: Helvetica Neue, Arial, sans-serif; font-size: 16px; font-weight: 300; max-width: 600px; position: relative'>
            <!-- top line -->
            <tr>
                <td colspan='2' style='padding: 16px; text-align: center;' width='160'><img id='logo' src='<?php echo SITE_DOMAIN ?>/<?php assets_dir() ?>/images/logo.png' style='height: auto;width: 180px;'></td>
            </tr>
            <!-- header -->
            <tr>
                <td bgcolor='#ffffff' colspan='2' style='color: #555; font-family: Helvetica Neue, Arial, sans-serif; font-size: 16px; font-weight: 300; line-height: 160%; padding: 16px 36px'>
                <strong style='font-weight: 700'>From:</strong> <?php echo $this->name ?><br>
                <strong style='font-weight: 700'>When:</strong> <?php echo $this->time ?> on <?php echo $this->date ?><br>
                <strong style='font-weight: 700'>Phone Number:</strong> <?php echo $this->phone ?><br>
                <div style='padding-top: 24px;'><?php echo $this->message ?></div>
                </td>
            </tr>
        </table>
    </div>
</div>

</body>
</html>
